### ISSUE TITLE
Potential to fix memory ordering for taken

### ISSUE THREAD

**Issue by wang384670111** [Darksonn/atomic-take#6]
https://github.com/Darksonn/atomic-take/blob/23d004fd789321652bfc0c2cf42f290a232999e3/src/lib.rs#L150-L151
Here, `token` is associated with `value` that must be synchronized with the access to `value`, but the code above does not use memory ordering to add reordering constraints. In a multithreaded environment, the following two pieces of code may not be synchronized for the read to `value`.

https://github.com/Darksonn/atomic-take/blob/23d004fd789321652bfc0c2cf42f290a232999e3/src/lib.rs#L117-L118
https://github.com/Darksonn/atomic-take/blob/23d004fd789321652bfc0c2cf42f290a232999e3/src/lib.rs#L163-L166

I think atomic operations on `token` require the use of Acquire/Relase, and modify this code as follows:
```
ptr::write(self.value.as_mut_ptr(), value); 
self.taken.store(false, Ordering::Release); 
```

```
if !self.taken.load(Ordering::Acquire) { 
     unsafe { 
         ptr::drop_in_place(self.value.as_mut_ptr()); 
     } 
```

**Comment by Darksonn** [comment]
Hi, thank you for opening this issue.

The `insert` method is `&mut self`, which means that the caller must synchronize access to the cell when they call it. That synchronization is enough to prevent any issues.
